<a href="https://colab.research.google.com/github/prasann-18/PimaIndiansDiabetesDatabase.ipynb/blob/main/PimaIndiansDiabetesDatabase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving archive (3).zip to archive (3) (3).zip


In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('archive (3).zip')

In [ ]:
# print first five data
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.shape

(768, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
(df == 0).any()

pregnancies                  True
glucose                     False
bloodpressure               False
skinthickness               False
insulin                     False
bmi                         False
diabetespedigreefunction    False
age                         False
outcome                      True
dtype: bool

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
# columns where 0 is not a valid medical vallue

invalid_zero_cols =[
    'glucose',
    'bloodpressure',
    'skinthickness',
    'insulin',
    'bmi'
]

# replace 0 with nan?
df[invalid_zero_cols] = df[invalid_zero_cols].replace(0, np.nan)

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
# impute missing values

for col in invalid_zero_cols:
  df[col].fillna(df[col].median(),inplace=True)


/tmp/ipython-input-252105041.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)


In [ ]:
# feature target separation

# feature
x = df.drop(columns = ['outcome'])

#target
y = df['outcome']

In [ ]:
x.columns

Index(['pregnancies', 'glucose', 'bloodpressure', 'skinthickness', 'insulin',
       'bmi', 'diabetespedigreefunction', 'age'],
      dtype='object')

In [ ]:
y.name

'outcome'

In [ ]:
#train and test split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42,stratify=y
)

In [ ]:
x_train.shape,x_test.shape

((614, 8), (154, 8))

In [ ]:
y.value_counts()

outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
y_train.value_counts(normalize=True)

outcome
0    0.651466
1    0.348534
Name: proportion, dtype: float64

In [ ]:
y_test.value_counts(normalize=True)

outcome
0    0.649351
1    0.350649
Name: proportion, dtype: float64

In [ ]:
# feature scaling -preprocessing

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_trian)
x_test_scaled = scaler.transform(x_test)

In [ ]:
# here using logistic regression classifier becasuse it is a
#  binary classification problem, strong baseline for medical data

from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train_scaled,y_train)

LogisticRegression()

In [ ]:
# prediction

y_pred = log_reg.predict(x_test_scaled)


In [ ]:
y_pred[:10]

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [ ]:
# accuracy of train

log_reg.score(x_train_scaled,y_train)

0.7964169381107492

In [ ]:
# liner regression probability prediction

y_prob = log_reg.predict_proba(x_test_scaled)


In [ ]:
y_prob[:20]

array([[0.39028927, 0.60971073],
       [0.88164424, 0.11835576],
       [0.70653687, 0.29346313],
       [0.7491633 , 0.2508367 ],
       [0.96679333, 0.03320667],
       [0.83147615, 0.16852385],
       [0.5118357 , 0.4881643 ],
       [0.07632489, 0.92367511],
       [0.91856595, 0.08143405],
       [0.1614104 , 0.8385896 ],
       [0.71899374, 0.28100626],
       [0.52026804, 0.47973196],
       [0.87078686, 0.12921314],
       [0.89824015, 0.10175985],
       [0.71148172, 0.28851828],
       [0.64772427, 0.35227573],
       [0.27674359, 0.72325641],
       [0.91551102, 0.08448898],
       [0.18674072, 0.81325928],
       [0.89115055, 0.10884945]])

In [ ]:
y_prob_diabetic = y_prob[:,1]
y_prob_diabetic[:10]

array([0.60971073, 0.11835576, 0.29346313, 0.2508367 , 0.03320667,
       0.16852385, 0.4881643 , 0.92367511, 0.08143405, 0.8385896 ])

In [ ]:
# confusion maatrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test,y_pred)
cm
# [TN FP]
# [FN TP]

# TN - True negative - actually non diabteic
# FP - false positive - actually non diabteic but predited diabetic
# FN - false negative - actually diabteic but predited diabetic
# TP - True positive - actually diabteic

array([[82, 18],
       [27, 27]])

In [ ]:
#classification report

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

# here we will see adout precision, recall, f1 score and support
# precision: how corrcet the model was when it said 0 or 1
# recall: how many real 0 and 1 it found
# f1:balance score of precisioon and recall
# support: how many actual 0 and 1 patients

# example for weighted avg
# classes with more sampples influence the final more
# than the smaller classes


              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154



In [ ]:
# next model we using here is SVM Support vector
# Machine , it finds a strong , margin based decision
# boundar that ofetn imporves recall on small,
# well sczlled datasets

# the main reason to use is dataset is samll in size,
# we did the scaling , chances are high to get betteer
# recall wath

In [ ]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear',probability=True)
svm_model.fit(x_train_scaled,y_train)


SVC(kernel='linear', probability=True)

In [ ]:
y_pred_svm = svm_model.predict(x_test_scaled)

#evaluating
svm_model.score(x_test_scaled,y_test)

0.7012987012987013

In [ ]:
svm_accuracy_prob=svm_model.predict_proba(x_test_scaled)
svm_accuracy_prob[:10]

array([[0.3914007 , 0.6085993 ],
       [0.87020636, 0.12979364],
       [0.68311463, 0.31688537],
       [0.73693736, 0.26306264],
       [0.9580619 , 0.0419381 ],
       [0.81439695, 0.18560305],
       [0.54027591, 0.45972409],
       [0.08454972, 0.91545028],
       [0.8989333 , 0.1010667 ],
       [0.18761562, 0.81238438]])

In [ ]:
y_prob_svm = svm_model.predict_proba(x_test_scaled)[:,1]


In [ ]:
y_prob_svm[:10]

array([0.6085993 , 0.12979364, 0.31688537, 0.26306264, 0.0419381 ,
       0.18560305, 0.45972409, 0.91545028, 0.1010667 , 0.81238438])

In [ ]:
# Confusion matrix

from sklearn.metrics import confusion_matrix
cm_svm = confusion_matrix(y_test,y_pred_svm)
cm_svm

array([[82, 18],
       [28, 26]])

In [ ]:
#classification reprot

print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.59      0.48      0.53        54

    accuracy                           0.70       154
   macro avg       0.67      0.65      0.66       154
weighted avg       0.69      0.70      0.69       154



In [ ]:
#ROC AUC Receiver Operating Cha

from sklearn.metrics import roc_auc_score
roc_auc_lr = roc_auc_score(y_test,y_prob[:,1])
roc_auc_svm = roc_auc_score(y_test,y_prob_svm)

roc_auc_lr,roc_auc_svm

#B1 for both lr and svm
# roc implies that both LR and SVM correctly ranks a diabetic higher
# that a non diadetic 82% of the time
# slides the thresholud from 0 =1, computer recall and false positives
# at each  step, plots the curve

(np.float64(0.812962962962963), np.float64(0.8134259259259259))